// Generated by CoffeeScript 1.6.3
var mongodb, setting;

setting = require("../settings");

mongodb = require("../models/db");

module.exports = function(app) {
  return app.get("/api/test", function(req, res) {
    return res.send("test");
  });
};
