# Generated by CoffeeScript 1.6.3
#mongodb = require("../lib/db")
mongoose = require '../lib/mongoose'
userSchema = new mongoose.Schema
  name:
    type: String
    index: true
    unique: true
  email:
    type: String
    index: true
    unique: true
  password: String
module.exports = User = mongoose.model 'User', userSchema
###User = (user) ->
  @username = user.username
  @email = user.email
  @password = user.password
  @id = ""

module.exports = User
###
User.save = (user,next)->
  user = new User user
  user.save()
  next null,user
###
User::save = (callback) ->
  user = undefined
  user =
    username: @username
    email: @email
    password: @password

  mongodb.open (err, db) ->
    callback err  if err
    db.collection "users", (err, collection) ->
      if err
        mongodb.close()
        callback err
      collection.ensureIndex "email",
        unique: true

      collection.insert user,
        safe: true
      , (arr, user) ->
        mongodb.close()
        callback err, user
User.get = (email, callback) ->
  mongodb.open (err, db) ->
    callback err  if err
    db.collection "users", (err, collection) ->
      if err
        mongodb.close()
        callback err
      collection.findOne
        email: email
      , (err, doc) ->
        mongodb.close()
        if doc
          user = new User(doc)
          callback err, user
        else
          callback err, null
###
User.get = (user,next)->
  next '201' if not user.email?
  User.findOne {email:user.email},(err,dbUser)->
    return next err if err
    if not dbUser?
      next err,null
    else
      next err,dbUser



