// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/

var apis, app, express, http, indexs, path;

express = require("express");

indexs = require("./routes");

apis = require("./routes/api");

http = require("http");

path = require("path");

app = express();

app.set("port", process.env.PORT || 3000);

app.set("views", __dirname + "/views");

app.set("view engine", "ejs");

app.use(express.favicon());

app.use(express.logger("dev"));

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(app.router);

app.use(express["static"](path.join(__dirname, "public")));

if ("development" === app.get("env")) {
  app.use(express.errorHandler());
}

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});

indexs(app);

apis(app);
