// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/

var api, app, express, http, path, routes;

express = require("express");

routes = require("./routes");

api = require("./routes/api");

http = require("http");

path = require("path");

app = express();

app.set("port", process.env.PORT || 3000);

app.set("views", __dirname + "/views");

app.set("view engine", "ejs");

app.use(express.favicon());

app.use(express.logger("dev"));

app.use(express.bodyParser());

app.use(express.methodOverride());

app.use(express.cookieParser("your secret here"));

app.use(express.session());

app.use(app.router);

app.use(require("stylus").middleware(__dirname + "/public"));

app.use(express["static"](path.join(__dirname, "public")));

if ("development" === app.get("env")) {
  app.use(express.errorHandler());
}

app.get("/", routes.index);

app.get("/api", api.index);

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});
